# Generated by Django 5.0.3 on 2024-03-06 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='tipoDocumento',
            field=models.CharField(default=1231, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='persona',
            name='numeroDocumento',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
