# Generated by Django 5.0.3 on 2024-03-06 22:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_persona', '0002_persona_tipodocumento_alter_persona_numerodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numeroDocumento',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator('^\\d{1,20}$')]),
        ),
    ]
