# Generated by Django 5.0.3 on 2024-03-06 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_persona', '0003_alter_persona_numerodocumento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nacionalidad',
            name='pais',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crear_persona.pais'),
        ),
    ]
