# Generated by Django 5.0.3 on 2024-03-07 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_persona', '0005_alter_usuario_options_alter_usuario_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='datos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crear_persona.persona'),
        ),
    ]
