# Generated by Django 5.0.3 on 2024-03-06 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crear_persona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TipoAntecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCertificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('cambios', models.TextField()),
                ('duenno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_persona.persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.tipocertificado')),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.provincia')),
            ],
        ),
        migrations.CreateModel(
            name='Antecedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('fechaAcontecimiento', models.DateTimeField()),
                ('usuarioRegistrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_persona.usuario')),
                ('certificado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.certificado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.departamento')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.distrito')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.provincia')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.tipoantecedente')),
            ],
        ),
    ]
