# Generated by Django 5.0.3 on 2024-03-06 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crear_antecedentes', '0002_departamento_pais_alter_distrito_nombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='antecedente',
            old_name='fechaAcontecimiento',
            new_name='fechaRegistro',
        ),
    ]
