# Generated by Django 5.0.3 on 2024-03-07 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_antecedentes', '0004_alter_certificado_version_historialcertificado'),
        ('crear_persona', '0004_alter_nacionalidad_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificado',
            name='duenno',
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duenno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crear_persona.persona')),
            ],
        ),
        migrations.AddField(
            model_name='certificado',
            name='historial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.bloque'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='HistorialCertificado',
        ),
    ]
