# Generated by Django 5.0.3 on 2024-03-07 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crear_antecedentes', '0005_remove_certificado_duenno_bloque_and_more'),
        ('crear_persona', '0004_alter_nacionalidad_pais'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Bloque',
            new_name='HistorialCertificado',
        ),
    ]
