# Generated by Django 5.0.3 on 2024-03-07 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crear_antecedentes', '0006_rename_bloque_historialcertificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialcertificado',
            name='num_certificados',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historialcertificado',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crear_antecedentes.tipocertificado'),
        ),
    ]
